package sk.hackcraft.bwu.types;

import javabot.JNIBWAPI;
import javabot.types.UnitType;

public class UnitTypes {
	final public UnitType Terran_Marine;
	final public UnitType Terran_Ghost;
	final public UnitType Terran_Vulture;
	final public UnitType Terran_Goliath;
	final public UnitType Terran_Siege_Tank_Tank_Mode;
	final public UnitType Terran_SCV;
	final public UnitType Terran_Wraith;
	final public UnitType Terran_Science_Vessel;
	final public UnitType Hero_Gui_Montag;
	final public UnitType Terran_Dropship;
	final public UnitType Terran_Battlecruiser;
	final public UnitType Terran_Vulture_Spider_Mine;
	final public UnitType Terran_Nuclear_Missile;
	final public UnitType Terran_Civilian;
	final public UnitType Hero_Sarah_Kerrigan;
	final public UnitType Hero_Alan_Schezar;
	final public UnitType Hero_Jim_Raynor_Vulture;
	final public UnitType Hero_Jim_Raynor_Marine;
	final public UnitType Hero_Tom_Kazansky;
	final public UnitType Hero_Magellan;
	final public UnitType Hero_Edmund_Duke_Tank_Mode;
	final public UnitType Hero_Edmund_Duke_Siege_Mode;
	final public UnitType Hero_Arcturus_Mengsk;
	final public UnitType Hero_Hyperion;
	final public UnitType Hero_Norad_II;
	final public UnitType Terran_Siege_Tank_Siege_Mode;
	final public UnitType Terran_Firebat;
	final public UnitType Spell_Scanner_Sweep;
	final public UnitType Terran_Medic;
	final public UnitType Zerg_Larva;
	final public UnitType Zerg_Egg;
	final public UnitType Zerg_Zergling;
	final public UnitType Zerg_Hydralisk;
	final public UnitType Zerg_Ultralisk;
	final public UnitType Zerg_Broodling;
	final public UnitType Zerg_Drone;
	final public UnitType Zerg_Overlord;
	final public UnitType Zerg_Mutalisk;
	final public UnitType Zerg_Guardian;
	final public UnitType Zerg_Queen;
	final public UnitType Zerg_Defiler;
	final public UnitType Zerg_Scourge;
	final public UnitType Hero_Torrasque;
	final public UnitType Hero_Matriarch;
	final public UnitType Zerg_Infested_Terran;
	final public UnitType Hero_Infested_Kerrigan;
	final public UnitType Hero_Unclean_One;
	final public UnitType Hero_Hunter_Killer;
	final public UnitType Hero_Devouring_One;
	final public UnitType Hero_Kukulza_Mutalisk;
	final public UnitType Hero_Kukulza_Guardian;
	final public UnitType Hero_Yggdrasill;
	final public UnitType Terran_Valkyrie;
	final public UnitType Zerg_Cocoon;
	final public UnitType Protoss_Corsair;
	final public UnitType Protoss_Dark_Templar;
	final public UnitType Zerg_Devourer;
	final public UnitType Protoss_Dark_Archon;
	final public UnitType Protoss_Probe;
	final public UnitType Protoss_Zealot;
	final public UnitType Protoss_Dragoon;
	final public UnitType Protoss_High_Templar;
	final public UnitType Protoss_Archon;
	final public UnitType Protoss_Shuttle;
	final public UnitType Protoss_Scout;
	final public UnitType Protoss_Arbiter;
	final public UnitType Protoss_Carrier;
	final public UnitType Protoss_Interceptor;
	final public UnitType Hero_Dark_Templar;
	final public UnitType Hero_Zeratul;
	final public UnitType Hero_Tassadar_Zeratul_Archon;
	final public UnitType Hero_Fenix_Zealot;
	final public UnitType Hero_Fenix_Dragoon;
	final public UnitType Hero_Tassadar;
	final public UnitType Hero_Mojo;
	final public UnitType Hero_Warbringer;
	final public UnitType Hero_Gantrithor;
	final public UnitType Protoss_Reaver;
	final public UnitType Protoss_Observer;
	final public UnitType Protoss_Scarab;
	final public UnitType Hero_Danimoth;
	final public UnitType Hero_Aldaris;
	final public UnitType Hero_Artanis;
	final public UnitType Critter_Rhynadon;
	final public UnitType Critter_Bengalaas;
	final public UnitType Critter_Scantid;
	final public UnitType Critter_Kakaru;
	final public UnitType Critter_Ragnasaur;
	final public UnitType Critter_Ursadon;
	final public UnitType Zerg_Lurker_Egg;
	final public UnitType Hero_Raszagal;
	final public UnitType Hero_Samir_Duran;
	final public UnitType Hero_Alexei_Stukov;
	final public UnitType Hero_Gerard_DuGalle;
	final public UnitType Zerg_Lurker;
	final public UnitType Hero_Infested_Duran;
	final public UnitType Spell_Disruption_Web;
	final public UnitType Terran_Command_Center;
	final public UnitType Terran_Comsat_Station;
	final public UnitType Terran_Nuclear_Silo;
	final public UnitType Terran_Supply_Depot;
	final public UnitType Terran_Refinery;
	final public UnitType Terran_Barracks;
	final public UnitType Terran_Academy;
	final public UnitType Terran_Factory;
	final public UnitType Terran_Starport;
	final public UnitType Terran_Control_Tower;
	final public UnitType Terran_Science_Facility;
	final public UnitType Terran_Covert_Ops;
	final public UnitType Terran_Physics_Lab;
	final public UnitType Terran_Machine_Shop;
	final public UnitType Terran_Engineering_Bay;
	final public UnitType Terran_Armory;
	final public UnitType Terran_Missile_Turret;
	final public UnitType Terran_Bunker;
	final public UnitType Special_Crashed_Norad_II;
	final public UnitType Special_Ion_Cannon;
	final public UnitType Powerup_Uraj_Crystal;
	final public UnitType Powerup_Khalis_Crystal;
	final public UnitType Zerg_Infested_Command_Center;
	final public UnitType Zerg_Hatchery;
	final public UnitType Zerg_Lair;
	final public UnitType Zerg_Hive;
	final public UnitType Zerg_Nydus_Canal;
	final public UnitType Zerg_Hydralisk_Den;
	final public UnitType Zerg_Defiler_Mound;
	final public UnitType Zerg_Greater_Spire;
	final public UnitType Zerg_Queens_Nest;
	final public UnitType Zerg_Evolution_Chamber;
	final public UnitType Zerg_Ultralisk_Cavern;
	final public UnitType Zerg_Spire;
	final public UnitType Zerg_Spawning_Pool;
	final public UnitType Zerg_Creep_Colony;
	final public UnitType Zerg_Spore_Colony;
	final public UnitType Zerg_Sunken_Colony;
	final public UnitType Special_Overmind_With_Shell;
	final public UnitType Special_Overmind;
	final public UnitType Zerg_Extractor;
	final public UnitType Special_Mature_Chrysalis;
	final public UnitType Special_Cerebrate;
	final public UnitType Special_Cerebrate_Daggoth;
	final public UnitType Protoss_Nexus;
	final public UnitType Protoss_Robotics_Facility;
	final public UnitType Protoss_Pylon;
	final public UnitType Protoss_Assimilator;
	final public UnitType Protoss_Observatory;
	final public UnitType Protoss_Gateway;
	final public UnitType Protoss_Photon_Cannon;
	final public UnitType Protoss_Citadel_of_Adun;
	final public UnitType Protoss_Cybernetics_Core;
	final public UnitType Protoss_Templar_Archives;
	final public UnitType Protoss_Forge;
	final public UnitType Protoss_Stargate;
	final public UnitType Special_Stasis_Cell_Prison;
	final public UnitType Protoss_Fleet_Beacon;
	final public UnitType Protoss_Arbiter_Tribunal;
	final public UnitType Protoss_Robotics_Support_Bay;
	final public UnitType Protoss_Shield_Battery;
	final public UnitType Special_Khaydarin_Crystal_Form;
	final public UnitType Special_Protoss_Temple;
	final public UnitType Special_XelNaga_Temple;
	final public UnitType Resource_Mineral_Field;
	final public UnitType Resource_Vespene_Geyser;
	final public UnitType Special_Warp_Gate;
	final public UnitType Special_Psi_Disrupter;
	final public UnitType Special_Zerg_Beacon;
	final public UnitType Special_Terran_Beacon;
	final public UnitType Special_Protoss_Beacon;
	final public UnitType Special_Zerg_Flag_Beacon;
	final public UnitType Special_Terran_Flag_Beacon;
	final public UnitType Special_Protoss_Flag_Beacon;
	final public UnitType Special_Power_Generator;
	final public UnitType Special_Overmind_Cocoon;
	final public UnitType Spell_Dark_Swarm;
	final public UnitType Powerup_Flag;
	final public UnitType Powerup_Young_Chrysalis;
	final public UnitType Powerup_Psi_Emitter;
	final public UnitType Powerup_Data_Disk;
	final public UnitType Powerup_Khaydarin_Crystal;
	final public UnitType None;
	final public UnitType Unknown;
	
	public UnitTypes(JNIBWAPI jnibwapi) {
		Terran_Marine = jnibwapi.getUnitType(0);
		Terran_Ghost = jnibwapi.getUnitType(1);
		Terran_Vulture = jnibwapi.getUnitType(2);
		Terran_Goliath = jnibwapi.getUnitType(3);
		Terran_Siege_Tank_Tank_Mode = jnibwapi.getUnitType(5);
		Terran_SCV = jnibwapi.getUnitType(7);
		Terran_Wraith = jnibwapi.getUnitType(8);
		Terran_Science_Vessel = jnibwapi.getUnitType(9);
		Hero_Gui_Montag = jnibwapi.getUnitType(10);
		Terran_Dropship = jnibwapi.getUnitType(11);
		Terran_Battlecruiser = jnibwapi.getUnitType(12);
		Terran_Vulture_Spider_Mine = jnibwapi.getUnitType(13);
		Terran_Nuclear_Missile = jnibwapi.getUnitType(14);
		Terran_Civilian = jnibwapi.getUnitType(15);
		Hero_Sarah_Kerrigan = jnibwapi.getUnitType(16);
		Hero_Alan_Schezar = jnibwapi.getUnitType(17);
		Hero_Jim_Raynor_Vulture = jnibwapi.getUnitType(19);
		Hero_Jim_Raynor_Marine = jnibwapi.getUnitType(20);
		Hero_Tom_Kazansky = jnibwapi.getUnitType(21);
		Hero_Magellan = jnibwapi.getUnitType(22);
		Hero_Edmund_Duke_Tank_Mode = jnibwapi.getUnitType(23);
		Hero_Edmund_Duke_Siege_Mode = jnibwapi.getUnitType(25);
		Hero_Arcturus_Mengsk = jnibwapi.getUnitType(27);
		Hero_Hyperion = jnibwapi.getUnitType(28);
		Hero_Norad_II = jnibwapi.getUnitType(29);
		Terran_Siege_Tank_Siege_Mode = jnibwapi.getUnitType(30);
		Terran_Firebat = jnibwapi.getUnitType(32);
		Spell_Scanner_Sweep = jnibwapi.getUnitType(33);
		Terran_Medic = jnibwapi.getUnitType(34);
		Zerg_Larva = jnibwapi.getUnitType(35);
		Zerg_Egg = jnibwapi.getUnitType(36);
		Zerg_Zergling = jnibwapi.getUnitType(37);
		Zerg_Hydralisk = jnibwapi.getUnitType(38);
		Zerg_Ultralisk = jnibwapi.getUnitType(39);
		Zerg_Broodling = jnibwapi.getUnitType(40);
		Zerg_Drone = jnibwapi.getUnitType(41);
		Zerg_Overlord = jnibwapi.getUnitType(42);
		Zerg_Mutalisk = jnibwapi.getUnitType(43);
		Zerg_Guardian = jnibwapi.getUnitType(44);
		Zerg_Queen = jnibwapi.getUnitType(45);
		Zerg_Defiler = jnibwapi.getUnitType(46);
		Zerg_Scourge = jnibwapi.getUnitType(47);
		Hero_Torrasque = jnibwapi.getUnitType(48);
		Hero_Matriarch = jnibwapi.getUnitType(49);
		Zerg_Infested_Terran = jnibwapi.getUnitType(50);
		Hero_Infested_Kerrigan = jnibwapi.getUnitType(51);
		Hero_Unclean_One = jnibwapi.getUnitType(52);
		Hero_Hunter_Killer = jnibwapi.getUnitType(53);
		Hero_Devouring_One = jnibwapi.getUnitType(54);
		Hero_Kukulza_Mutalisk = jnibwapi.getUnitType(55);
		Hero_Kukulza_Guardian = jnibwapi.getUnitType(56);
		Hero_Yggdrasill = jnibwapi.getUnitType(57);
		Terran_Valkyrie = jnibwapi.getUnitType(58);
		Zerg_Cocoon = jnibwapi.getUnitType(59);
		Protoss_Corsair = jnibwapi.getUnitType(60);
		Protoss_Dark_Templar = jnibwapi.getUnitType(61);
		Zerg_Devourer = jnibwapi.getUnitType(62);
		Protoss_Dark_Archon = jnibwapi.getUnitType(63);
		Protoss_Probe = jnibwapi.getUnitType(64);
		Protoss_Zealot = jnibwapi.getUnitType(65);
		Protoss_Dragoon = jnibwapi.getUnitType(66);
		Protoss_High_Templar = jnibwapi.getUnitType(67);
		Protoss_Archon = jnibwapi.getUnitType(68);
		Protoss_Shuttle = jnibwapi.getUnitType(69);
		Protoss_Scout = jnibwapi.getUnitType(70);
		Protoss_Arbiter = jnibwapi.getUnitType(71);
		Protoss_Carrier = jnibwapi.getUnitType(72);
		Protoss_Interceptor = jnibwapi.getUnitType(73);
		Hero_Dark_Templar = jnibwapi.getUnitType(74);
		Hero_Zeratul = jnibwapi.getUnitType(75);
		Hero_Tassadar_Zeratul_Archon = jnibwapi.getUnitType(76);
		Hero_Fenix_Zealot = jnibwapi.getUnitType(77);
		Hero_Fenix_Dragoon = jnibwapi.getUnitType(78);
		Hero_Tassadar = jnibwapi.getUnitType(79);
		Hero_Mojo = jnibwapi.getUnitType(80);
		Hero_Warbringer = jnibwapi.getUnitType(81);
		Hero_Gantrithor = jnibwapi.getUnitType(82);
		Protoss_Reaver = jnibwapi.getUnitType(83);
		Protoss_Observer = jnibwapi.getUnitType(84);
		Protoss_Scarab = jnibwapi.getUnitType(85);
		Hero_Danimoth = jnibwapi.getUnitType(86);
		Hero_Aldaris = jnibwapi.getUnitType(87);
		Hero_Artanis = jnibwapi.getUnitType(88);
		Critter_Rhynadon = jnibwapi.getUnitType(89);
		Critter_Bengalaas = jnibwapi.getUnitType(90);
		Critter_Scantid = jnibwapi.getUnitType(93);
		Critter_Kakaru = jnibwapi.getUnitType(94);
		Critter_Ragnasaur = jnibwapi.getUnitType(95);
		Critter_Ursadon = jnibwapi.getUnitType(96);
		Zerg_Lurker_Egg = jnibwapi.getUnitType(97);
		Hero_Raszagal = jnibwapi.getUnitType(98);
		Hero_Samir_Duran = jnibwapi.getUnitType(99);
		Hero_Alexei_Stukov = jnibwapi.getUnitType(100);
		Hero_Gerard_DuGalle = jnibwapi.getUnitType(102);
		Zerg_Lurker = jnibwapi.getUnitType(103);
		Hero_Infested_Duran = jnibwapi.getUnitType(104);
		Spell_Disruption_Web = jnibwapi.getUnitType(105);
		Terran_Command_Center = jnibwapi.getUnitType(106);
		Terran_Comsat_Station = jnibwapi.getUnitType(107);
		Terran_Nuclear_Silo = jnibwapi.getUnitType(108);
		Terran_Supply_Depot = jnibwapi.getUnitType(109);
		Terran_Refinery = jnibwapi.getUnitType(110);
		Terran_Barracks = jnibwapi.getUnitType(111);
		Terran_Academy = jnibwapi.getUnitType(112);
		Terran_Factory = jnibwapi.getUnitType(113);
		Terran_Starport = jnibwapi.getUnitType(114);
		Terran_Control_Tower = jnibwapi.getUnitType(115);
		Terran_Science_Facility = jnibwapi.getUnitType(116);
		Terran_Covert_Ops = jnibwapi.getUnitType(117);
		Terran_Physics_Lab = jnibwapi.getUnitType(118);
		Terran_Machine_Shop = jnibwapi.getUnitType(120);
		Terran_Engineering_Bay = jnibwapi.getUnitType(122);
		Terran_Armory = jnibwapi.getUnitType(123);
		Terran_Missile_Turret = jnibwapi.getUnitType(124);
		Terran_Bunker = jnibwapi.getUnitType(125);
		Special_Crashed_Norad_II = jnibwapi.getUnitType(126);
		Special_Ion_Cannon = jnibwapi.getUnitType(127);
		Powerup_Uraj_Crystal = jnibwapi.getUnitType(128);
		Powerup_Khalis_Crystal = jnibwapi.getUnitType(129);
		Zerg_Infested_Command_Center = jnibwapi.getUnitType(130);
		Zerg_Hatchery = jnibwapi.getUnitType(131);
		Zerg_Lair = jnibwapi.getUnitType(132);
		Zerg_Hive = jnibwapi.getUnitType(133);
		Zerg_Nydus_Canal = jnibwapi.getUnitType(134);
		Zerg_Hydralisk_Den = jnibwapi.getUnitType(135);
		Zerg_Defiler_Mound = jnibwapi.getUnitType(136);
		Zerg_Greater_Spire = jnibwapi.getUnitType(137);
		Zerg_Queens_Nest = jnibwapi.getUnitType(138);
		Zerg_Evolution_Chamber = jnibwapi.getUnitType(139);
		Zerg_Ultralisk_Cavern = jnibwapi.getUnitType(140);
		Zerg_Spire = jnibwapi.getUnitType(141);
		Zerg_Spawning_Pool = jnibwapi.getUnitType(142);
		Zerg_Creep_Colony = jnibwapi.getUnitType(143);
		Zerg_Spore_Colony = jnibwapi.getUnitType(144);
		Zerg_Sunken_Colony = jnibwapi.getUnitType(146);
		Special_Overmind_With_Shell = jnibwapi.getUnitType(147);
		Special_Overmind = jnibwapi.getUnitType(148);
		Zerg_Extractor = jnibwapi.getUnitType(149);
		Special_Mature_Chrysalis = jnibwapi.getUnitType(150);
		Special_Cerebrate = jnibwapi.getUnitType(151);
		Special_Cerebrate_Daggoth = jnibwapi.getUnitType(152);
		Protoss_Nexus = jnibwapi.getUnitType(154);
		Protoss_Robotics_Facility = jnibwapi.getUnitType(155);
		Protoss_Pylon = jnibwapi.getUnitType(156);
		Protoss_Assimilator = jnibwapi.getUnitType(157);
		Protoss_Observatory = jnibwapi.getUnitType(159);
		Protoss_Gateway = jnibwapi.getUnitType(160);
		Protoss_Photon_Cannon = jnibwapi.getUnitType(162);
		Protoss_Citadel_of_Adun = jnibwapi.getUnitType(163);
		Protoss_Cybernetics_Core = jnibwapi.getUnitType(164);
		Protoss_Templar_Archives = jnibwapi.getUnitType(165);
		Protoss_Forge = jnibwapi.getUnitType(166);
		Protoss_Stargate = jnibwapi.getUnitType(167);
		Special_Stasis_Cell_Prison = jnibwapi.getUnitType(168);
		Protoss_Fleet_Beacon = jnibwapi.getUnitType(169);
		Protoss_Arbiter_Tribunal = jnibwapi.getUnitType(170);
		Protoss_Robotics_Support_Bay = jnibwapi.getUnitType(171);
		Protoss_Shield_Battery = jnibwapi.getUnitType(172);
		Special_Khaydarin_Crystal_Form = jnibwapi.getUnitType(173);
		Special_Protoss_Temple = jnibwapi.getUnitType(174);
		Special_XelNaga_Temple = jnibwapi.getUnitType(175);
		Resource_Mineral_Field = jnibwapi.getUnitType(176);
		Resource_Vespene_Geyser = jnibwapi.getUnitType(188);
		Special_Warp_Gate = jnibwapi.getUnitType(189);
		Special_Psi_Disrupter = jnibwapi.getUnitType(190);
		Special_Zerg_Beacon = jnibwapi.getUnitType(194);
		Special_Terran_Beacon = jnibwapi.getUnitType(195);
		Special_Protoss_Beacon = jnibwapi.getUnitType(196);
		Special_Zerg_Flag_Beacon = jnibwapi.getUnitType(197);
		Special_Terran_Flag_Beacon = jnibwapi.getUnitType(198);
		Special_Protoss_Flag_Beacon = jnibwapi.getUnitType(199);
		Special_Power_Generator = jnibwapi.getUnitType(200);
		Special_Overmind_Cocoon = jnibwapi.getUnitType(201);
		Spell_Dark_Swarm = jnibwapi.getUnitType(202);
		Powerup_Flag = jnibwapi.getUnitType(215);
		Powerup_Young_Chrysalis = jnibwapi.getUnitType(216);
		Powerup_Psi_Emitter = jnibwapi.getUnitType(217);
		Powerup_Data_Disk = jnibwapi.getUnitType(218);
		Powerup_Khaydarin_Crystal = jnibwapi.getUnitType(219);
		None = jnibwapi.getUnitType(228);
		Unknown = jnibwapi.getUnitType(233);
	}
}
