package sk.hackcraft.bwu.types;

import javabot.JNIBWAPI;
import javabot.types.UpgradeType;

public class UpgradeTypes {
	final public UpgradeType Terran_Infantry_Armor;
	final public UpgradeType Terran_Vehicle_Plating;
	final public UpgradeType Terran_Ship_Plating;
	final public UpgradeType Zerg_Carapace;
	final public UpgradeType Zerg_Flyer_Carapace;
	final public UpgradeType Protoss_Ground_Armor;
	final public UpgradeType Protoss_Air_Armor;
	final public UpgradeType Terran_Infantry_Weapons;
	final public UpgradeType Terran_Vehicle_Weapons;
	final public UpgradeType Terran_Ship_Weapons;
	final public UpgradeType Zerg_Melee_Attacks;
	final public UpgradeType Zerg_Missile_Attacks;
	final public UpgradeType Zerg_Flyer_Attacks;
	final public UpgradeType Protoss_Ground_Weapons;
	final public UpgradeType Protoss_Air_Weapons;
	final public UpgradeType Protoss_Plasma_Shields;
	final public UpgradeType U_238_Shells;
	final public UpgradeType Ion_Thrusters;
	final public UpgradeType Undefined18;
	final public UpgradeType Titan_Reactor;
	final public UpgradeType Ocular_Implants;
	final public UpgradeType Moebius_Reactor;
	final public UpgradeType Apollo_Reactor;
	final public UpgradeType Colossus_Reactor;
	final public UpgradeType Ventral_Sacs;
	final public UpgradeType Antennae;
	final public UpgradeType Pneumatized_Carapace;
	final public UpgradeType Metabolic_Boost;
	final public UpgradeType Adrenal_Glands;
	final public UpgradeType Muscular_Augments;
	final public UpgradeType Grooved_Spines;
	final public UpgradeType Gamete_Meiosis;
	final public UpgradeType Metasynaptic_Node;
	final public UpgradeType Singularity_Charge;
	final public UpgradeType Leg_Enhancements;
	final public UpgradeType Scarab_Damage;
	final public UpgradeType Reaver_Capacity;
	final public UpgradeType Gravitic_Drive;
	final public UpgradeType Sensor_Array;
	final public UpgradeType Gravitic_Boosters;
	final public UpgradeType Khaydarin_Amulet;
	final public UpgradeType Apial_Sensors;
	final public UpgradeType Gravitic_Thrusters;
	final public UpgradeType Carrier_Capacity;
	final public UpgradeType Khaydarin_Core;
	final public UpgradeType Undefined45;
	final public UpgradeType Undefined46;
	final public UpgradeType Argus_Jewel;
	final public UpgradeType Undefined48;
	final public UpgradeType Argus_Talisman;
	final public UpgradeType Undefined50;
	final public UpgradeType Caduceus_Reactor;
	final public UpgradeType Chitinous_Plating;
	final public UpgradeType Anabolic_Synthesis;
	final public UpgradeType Charon_Boosters;
	final public UpgradeType Undefined55;
	final public UpgradeType Undefined56;
	final public UpgradeType Undefined57;
	final public UpgradeType Undefined58;
	final public UpgradeType Undefined59;
	final public UpgradeType Undefined60;
	final public UpgradeType None;
	final public UpgradeType Unknown;
	
	public UpgradeTypes(JNIBWAPI jnibwapi) {
		Terran_Infantry_Armor = jnibwapi.getUpgradeType(0);
		Terran_Vehicle_Plating = jnibwapi.getUpgradeType(1);
		Terran_Ship_Plating = jnibwapi.getUpgradeType(2);
		Zerg_Carapace = jnibwapi.getUpgradeType(3);
		Zerg_Flyer_Carapace = jnibwapi.getUpgradeType(4);
		Protoss_Ground_Armor = jnibwapi.getUpgradeType(5);
		Protoss_Air_Armor = jnibwapi.getUpgradeType(6);
		Terran_Infantry_Weapons = jnibwapi.getUpgradeType(7);
		Terran_Vehicle_Weapons = jnibwapi.getUpgradeType(8);
		Terran_Ship_Weapons = jnibwapi.getUpgradeType(9);
		Zerg_Melee_Attacks = jnibwapi.getUpgradeType(10);
		Zerg_Missile_Attacks = jnibwapi.getUpgradeType(11);
		Zerg_Flyer_Attacks = jnibwapi.getUpgradeType(12);
		Protoss_Ground_Weapons = jnibwapi.getUpgradeType(13);
		Protoss_Air_Weapons = jnibwapi.getUpgradeType(14);
		Protoss_Plasma_Shields = jnibwapi.getUpgradeType(15);
		U_238_Shells = jnibwapi.getUpgradeType(16);
		Ion_Thrusters = jnibwapi.getUpgradeType(17);
		Undefined18 = jnibwapi.getUpgradeType(18);
		Titan_Reactor = jnibwapi.getUpgradeType(19);
		Ocular_Implants = jnibwapi.getUpgradeType(20);
		Moebius_Reactor = jnibwapi.getUpgradeType(21);
		Apollo_Reactor = jnibwapi.getUpgradeType(22);
		Colossus_Reactor = jnibwapi.getUpgradeType(23);
		Ventral_Sacs = jnibwapi.getUpgradeType(24);
		Antennae = jnibwapi.getUpgradeType(25);
		Pneumatized_Carapace = jnibwapi.getUpgradeType(26);
		Metabolic_Boost = jnibwapi.getUpgradeType(27);
		Adrenal_Glands = jnibwapi.getUpgradeType(28);
		Muscular_Augments = jnibwapi.getUpgradeType(29);
		Grooved_Spines = jnibwapi.getUpgradeType(30);
		Gamete_Meiosis = jnibwapi.getUpgradeType(31);
		Metasynaptic_Node = jnibwapi.getUpgradeType(32);
		Singularity_Charge = jnibwapi.getUpgradeType(33);
		Leg_Enhancements = jnibwapi.getUpgradeType(34);
		Scarab_Damage = jnibwapi.getUpgradeType(35);
		Reaver_Capacity = jnibwapi.getUpgradeType(36);
		Gravitic_Drive = jnibwapi.getUpgradeType(37);
		Sensor_Array = jnibwapi.getUpgradeType(38);
		Gravitic_Boosters = jnibwapi.getUpgradeType(39);
		Khaydarin_Amulet = jnibwapi.getUpgradeType(40);
		Apial_Sensors = jnibwapi.getUpgradeType(41);
		Gravitic_Thrusters = jnibwapi.getUpgradeType(42);
		Carrier_Capacity = jnibwapi.getUpgradeType(43);
		Khaydarin_Core = jnibwapi.getUpgradeType(44);
		Undefined45 = jnibwapi.getUpgradeType(45);
		Undefined46 = jnibwapi.getUpgradeType(46);
		Argus_Jewel = jnibwapi.getUpgradeType(47);
		Undefined48 = jnibwapi.getUpgradeType(48);
		Argus_Talisman = jnibwapi.getUpgradeType(49);
		Undefined50 = jnibwapi.getUpgradeType(50);
		Caduceus_Reactor = jnibwapi.getUpgradeType(51);
		Chitinous_Plating = jnibwapi.getUpgradeType(52);
		Anabolic_Synthesis = jnibwapi.getUpgradeType(53);
		Charon_Boosters = jnibwapi.getUpgradeType(54);
		Undefined55 = jnibwapi.getUpgradeType(55);
		Undefined56 = jnibwapi.getUpgradeType(56);
		Undefined57 = jnibwapi.getUpgradeType(57);
		Undefined58 = jnibwapi.getUpgradeType(58);
		Undefined59 = jnibwapi.getUpgradeType(59);
		Undefined60 = jnibwapi.getUpgradeType(60);
		None = jnibwapi.getUpgradeType(61);
		Unknown = jnibwapi.getUpgradeType(62);
	}
}
