package sk.hackcraft.bwu;

import javabot.JNIBWAPI;
import javabot.types.OrderType;

public class OrderTypes {
    final public OrderType Die;
    final public OrderType Stop;
    final public OrderType Guard;
    final public OrderType PlayerGuard;
    final public OrderType TurretGuard;
    final public OrderType BunkerGuard;
    final public OrderType Move;
    final public OrderType AttackUnit;
    final public OrderType AttackTile;
    final public OrderType Hover;
    final public OrderType AttackMove;
    final public OrderType InfestedCommandCenter;
    final public OrderType UnusedNothing;
    final public OrderType UnusedPowerup;
    final public OrderType TowerGuard;
    final public OrderType VultureMine;
    final public OrderType Nothing;
    final public OrderType Nothing3;
    final public OrderType CastInfestation;
    final public OrderType InfestingCommandCenter;
    final public OrderType PlaceBuilding;
    final public OrderType BuildProtoss2;
    final public OrderType ConstructingBuilding;
    final public OrderType Repair;
    final public OrderType PlaceAddon;
    final public OrderType BuildAddon;
    final public OrderType Train;
    final public OrderType RallyPointUnit;
    final public OrderType RallyPointTile;
    final public OrderType ZergBirth;
    final public OrderType ZergUnitMorph;
    final public OrderType ZergBuildingMorph;
    final public OrderType IncompleteBuilding;
    final public OrderType BuildNydusExit;
    final public OrderType EnterNydusCanal;
    final public OrderType Follow;
    final public OrderType Carrier;
    final public OrderType ReaverCarrierMove;
    final public OrderType CarrierIgnore2;
    final public OrderType Reaver;
    final public OrderType TrainFighter;
    final public OrderType InterceptorAttack;
    final public OrderType ScarabAttack;
    final public OrderType RechargeShieldsUnit;
    final public OrderType RechargeShieldsBattery;
    final public OrderType ShieldBattery;
    final public OrderType InterceptorReturn;
    final public OrderType BuildingLand;
    final public OrderType BuildingLiftOff;
    final public OrderType DroneLiftOff;
    final public OrderType LiftingOff;
    final public OrderType ResearchTech;
    final public OrderType Upgrade;
    final public OrderType Larva;
    final public OrderType SpawningLarva;
    final public OrderType Harvest1;
    final public OrderType Harvest2;
    final public OrderType MoveToGas; //- Unit is moving to refinery
    final public OrderType WaitForGas; // - Unit is waiting to enter the refinery (another unit is currently in it)
    final public OrderType HarvestGas; //- Unit is in refinery
    final public OrderType ReturnGas; //- Unit is returning gas to center
    final public OrderType MoveToMinerals;// - Unit is moving to mineral patch
    final public OrderType WaitForMinerals;// - Unit is waiting to use the mineral patch (another unit is currently mining from it)
    final public OrderType MiningMinerals;// - Unit is mining minerals from mineral patch
    final public OrderType Harvest3;
    final public OrderType Harvest4;
    final public OrderType ReturnMinerals; // - Unit is returning minerals to center
    final public OrderType Interrupted;
    final public OrderType EnterTransport;
    final public OrderType PickupIdle;
    final public OrderType PickupTransport;
    final public OrderType PickupBunker;
    final public OrderType Pickup4;
    final public OrderType PowerupIdle;
    final public OrderType Sieging;
    final public OrderType Unsieging;
    final public OrderType InitCreepGrowth;
    final public OrderType SpreadCreep;
    final public OrderType StoppingCreepGrowth;
    final public OrderType GuardianAspect;
    final public OrderType ArchonWarp;
    final public OrderType CompletingArchonsummon;
    final public OrderType HoldPosition;
    final public OrderType Cloak;
    final public OrderType Decloak;
    final public OrderType Unload;
    final public OrderType MoveUnload;
    final public OrderType FireYamatoGun;
    final public OrderType CastLockdown;
    final public OrderType Burrowing;
    final public OrderType Burrowed;
    final public OrderType Unburrowing;
    final public OrderType CastDarkSwarm;
    final public OrderType CastParasite;
    final public OrderType CastSpawnBroodlings;
    final public OrderType CastEMPShockwave;
    final public OrderType NukeWait;
    final public OrderType NukeTrain;
    final public OrderType NukeLaunch;
    final public OrderType NukeUnit;
    final public OrderType CastNuclearStrike;
    final public OrderType NukeTrack;
    final public OrderType CloakNearbyUnits;
    final public OrderType PlaceMine;
    final public OrderType RightClickAction;
    final public OrderType CastRecall;
    final public OrderType TeleporttoLocation;
    final public OrderType CastScannerSweep;
    final public OrderType Scanner;
    final public OrderType CastDefensiveMatrix;
    final public OrderType CastPsionicStorm;
    final public OrderType CastIrradiate;
    final public OrderType CastPlague;
    final public OrderType CastConsume;
    final public OrderType CastEnsnare;
    final public OrderType CastStasisField;
    final public OrderType CastHallucination;
    final public OrderType Hallucination2;
    final public OrderType ResetCollision;
    final public OrderType Patrol;
    final public OrderType CTFCOPInit;
    final public OrderType CTFCOP1;
    final public OrderType CTFCOP2;
    final public OrderType ComputerAI;
    final public OrderType AtkMoveEP;
    final public OrderType HarassMove;
    final public OrderType AIPatrol;
    final public OrderType GuardPost;
    final public OrderType RescuePassive;
    final public OrderType Neutral;
    final public OrderType ComputerReturn;
    final public OrderType SelfDestrucing;
    final public OrderType Critter;
    final public OrderType HiddenGun;
    final public OrderType OpenDoor;
    final public OrderType CloseDoor;
    final public OrderType HideTrap;
    final public OrderType RevealTrap;
    final public OrderType Enabledoodad;
    final public OrderType Disabledoodad;
    final public OrderType Warpin;
    final public OrderType Medic;
    final public OrderType MedicHeal1;
    final public OrderType HealMove;
    final public OrderType MedicHeal2;
    final public OrderType CastRestoration;
    final public OrderType CastDisruptionWeb;
    final public OrderType CastMindControl;
    final public OrderType DarkArchonMeld;
    final public OrderType CastFeedback;
    final public OrderType CastOpticalFlare;
    final public OrderType CastMaelstrom;
    final public OrderType JunkYardDog;
    final public OrderType Fatal;
    final public OrderType None;
    final public OrderType Unknown;
    
    protected OrderTypes(JNIBWAPI jnibwapi) {
    	Die = jnibwapi.getOrderType(0);
	    Stop = jnibwapi.getOrderType(1);
	    Guard = jnibwapi.getOrderType(2);
	    PlayerGuard = jnibwapi.getOrderType(3);
	    TurretGuard = jnibwapi.getOrderType(4);
	    BunkerGuard = jnibwapi.getOrderType(5);
	    Move = jnibwapi.getOrderType(6);
	    AttackUnit = jnibwapi.getOrderType(7);
	    AttackTile = jnibwapi.getOrderType(8);
	    Hover = jnibwapi.getOrderType(9);
	    AttackMove = jnibwapi.getOrderType(10);
	    InfestedCommandCenter = jnibwapi.getOrderType(11);
	    UnusedNothing = jnibwapi.getOrderType(12);
	    UnusedPowerup = jnibwapi.getOrderType(13);
	    TowerGuard = jnibwapi.getOrderType(14);
	    VultureMine = jnibwapi.getOrderType(15);
	    Nothing = jnibwapi.getOrderType(16);
	    Nothing3 = jnibwapi.getOrderType(17);
	    CastInfestation = jnibwapi.getOrderType(18);
	    InfestingCommandCenter = jnibwapi.getOrderType(19);
	    PlaceBuilding = jnibwapi.getOrderType(20);
	    BuildProtoss2 = jnibwapi.getOrderType(21);
	    ConstructingBuilding = jnibwapi.getOrderType(22);
	    Repair = jnibwapi.getOrderType(23);
	    PlaceAddon = jnibwapi.getOrderType(24);
	    BuildAddon = jnibwapi.getOrderType(25);
	    Train = jnibwapi.getOrderType(26);
	    RallyPointUnit = jnibwapi.getOrderType(27);
	    RallyPointTile = jnibwapi.getOrderType(28);
	    ZergBirth = jnibwapi.getOrderType(29);
	    ZergUnitMorph = jnibwapi.getOrderType(30);
	    ZergBuildingMorph = jnibwapi.getOrderType(31);
	    IncompleteBuilding = jnibwapi.getOrderType(32);
	    BuildNydusExit = jnibwapi.getOrderType(33);
	    EnterNydusCanal = jnibwapi.getOrderType(34);
	    Follow = jnibwapi.getOrderType(35);
	    Carrier = jnibwapi.getOrderType(36);
	    ReaverCarrierMove = jnibwapi.getOrderType(37);
	    CarrierIgnore2 = jnibwapi.getOrderType(38);
	    Reaver = jnibwapi.getOrderType(39);
	    TrainFighter = jnibwapi.getOrderType(40);
	    InterceptorAttack = jnibwapi.getOrderType(41);
	    ScarabAttack = jnibwapi.getOrderType(42);
	    RechargeShieldsUnit = jnibwapi.getOrderType(43);
	    RechargeShieldsBattery = jnibwapi.getOrderType(44);
	    ShieldBattery = jnibwapi.getOrderType(45);
	    InterceptorReturn = jnibwapi.getOrderType(46);
	    BuildingLand = jnibwapi.getOrderType(47);
	    BuildingLiftOff = jnibwapi.getOrderType(48);
	    DroneLiftOff = jnibwapi.getOrderType(49);
	    LiftingOff = jnibwapi.getOrderType(50);
	    ResearchTech = jnibwapi.getOrderType(51);
	    Upgrade = jnibwapi.getOrderType(52);
	    Larva = jnibwapi.getOrderType(53);
	    SpawningLarva = jnibwapi.getOrderType(54);
	    Harvest1 = jnibwapi.getOrderType(55);
	    Harvest2 = jnibwapi.getOrderType(56);
	    MoveToGas = jnibwapi.getOrderType(57); //- Unit is moving to refinery
	    WaitForGas = jnibwapi.getOrderType(58); // - Unit is waiting to enter the refinery (another unit is currently in it)
	    HarvestGas = jnibwapi.getOrderType(59); //- Unit is in refinery
	    ReturnGas = jnibwapi.getOrderType(60); //- Unit is returning gas to center
	    MoveToMinerals = jnibwapi.getOrderType(61);// - Unit is moving to mineral patch
	    WaitForMinerals = jnibwapi.getOrderType(62);// - Unit is waiting to use the mineral patch (another unit is currently mining from it)
	    MiningMinerals = jnibwapi.getOrderType(63);// - Unit is mining minerals from mineral patch
	    Harvest3 = jnibwapi.getOrderType(64);
	    Harvest4 = jnibwapi.getOrderType(65);
	    ReturnMinerals = jnibwapi.getOrderType(66); // - Unit is returning minerals to center
	    Interrupted = jnibwapi.getOrderType(67);
	    EnterTransport = jnibwapi.getOrderType(68);
	    PickupIdle = jnibwapi.getOrderType(69);
	    PickupTransport = jnibwapi.getOrderType(70);
	    PickupBunker = jnibwapi.getOrderType(71);
	    Pickup4 = jnibwapi.getOrderType(72);
	    PowerupIdle = jnibwapi.getOrderType(73);
	    Sieging = jnibwapi.getOrderType(74);
	    Unsieging = jnibwapi.getOrderType(75);
	    InitCreepGrowth = jnibwapi.getOrderType(76);
	    SpreadCreep = jnibwapi.getOrderType(77);
	    StoppingCreepGrowth = jnibwapi.getOrderType(78);
	    GuardianAspect = jnibwapi.getOrderType(79);
	    ArchonWarp = jnibwapi.getOrderType(80);
	    CompletingArchonsummon = jnibwapi.getOrderType(81);
	    HoldPosition = jnibwapi.getOrderType(82);
	    Cloak = jnibwapi.getOrderType(83);
	    Decloak = jnibwapi.getOrderType(84);
	    Unload = jnibwapi.getOrderType(85);
	    MoveUnload = jnibwapi.getOrderType(86);
	    FireYamatoGun = jnibwapi.getOrderType(87);
	    CastLockdown = jnibwapi.getOrderType(88);
	    Burrowing = jnibwapi.getOrderType(89);
	    Burrowed = jnibwapi.getOrderType(90);
	    Unburrowing = jnibwapi.getOrderType(91);
	    CastDarkSwarm = jnibwapi.getOrderType(92);
	    CastParasite = jnibwapi.getOrderType(93);
	    CastSpawnBroodlings = jnibwapi.getOrderType(94);
	    CastEMPShockwave = jnibwapi.getOrderType(95);
	    NukeWait = jnibwapi.getOrderType(96);
	    NukeTrain = jnibwapi.getOrderType(97);
	    NukeLaunch = jnibwapi.getOrderType(98);
	    NukeUnit = jnibwapi.getOrderType(99);
	    CastNuclearStrike = jnibwapi.getOrderType(100);
	    NukeTrack = jnibwapi.getOrderType(101);
	    CloakNearbyUnits = jnibwapi.getOrderType(102);
	    PlaceMine = jnibwapi.getOrderType(103);
	    RightClickAction = jnibwapi.getOrderType(104);
	    CastRecall = jnibwapi.getOrderType(105);
	    TeleporttoLocation = jnibwapi.getOrderType(106);
	    CastScannerSweep = jnibwapi.getOrderType(107);
	    Scanner = jnibwapi.getOrderType(108);
	    CastDefensiveMatrix = jnibwapi.getOrderType(109);
	    CastPsionicStorm = jnibwapi.getOrderType(110);
	    CastIrradiate = jnibwapi.getOrderType(111);
	    CastPlague = jnibwapi.getOrderType(112);
	    CastConsume = jnibwapi.getOrderType(113);
	    CastEnsnare = jnibwapi.getOrderType(114);
	    CastStasisField = jnibwapi.getOrderType(115);
	    CastHallucination = jnibwapi.getOrderType(116);
	    Hallucination2 = jnibwapi.getOrderType(117);
	    ResetCollision = jnibwapi.getOrderType(118);
	    Patrol = jnibwapi.getOrderType(119);
	    CTFCOPInit = jnibwapi.getOrderType(120);
	    CTFCOP1 = jnibwapi.getOrderType(121);
	    CTFCOP2 = jnibwapi.getOrderType(122);
	    ComputerAI = jnibwapi.getOrderType(123);
	    AtkMoveEP = jnibwapi.getOrderType(124);
	    HarassMove = jnibwapi.getOrderType(125);
	    AIPatrol = jnibwapi.getOrderType(126);
	    GuardPost = jnibwapi.getOrderType(127);
	    RescuePassive = jnibwapi.getOrderType(128);
	    Neutral = jnibwapi.getOrderType(129);
	    ComputerReturn = jnibwapi.getOrderType(130);
	    SelfDestrucing = jnibwapi.getOrderType(131);
	    Critter = jnibwapi.getOrderType(132);
	    HiddenGun = jnibwapi.getOrderType(133);
	    OpenDoor = jnibwapi.getOrderType(134);
	    CloseDoor = jnibwapi.getOrderType(135);
	    HideTrap = jnibwapi.getOrderType(136);
	    RevealTrap = jnibwapi.getOrderType(137);
	    Enabledoodad = jnibwapi.getOrderType(138);
	    Disabledoodad = jnibwapi.getOrderType(139);
	    Warpin = jnibwapi.getOrderType(140);
	    Medic = jnibwapi.getOrderType(141);
	    MedicHeal1 = jnibwapi.getOrderType(142);
	    HealMove = jnibwapi.getOrderType(143);
	    MedicHeal2 = jnibwapi.getOrderType(144);
	    CastRestoration = jnibwapi.getOrderType(145);
	    CastDisruptionWeb = jnibwapi.getOrderType(146);
	    CastMindControl = jnibwapi.getOrderType(147);
	    DarkArchonMeld = jnibwapi.getOrderType(148);
	    CastFeedback = jnibwapi.getOrderType(149);
	    CastOpticalFlare = jnibwapi.getOrderType(150);
	    CastMaelstrom = jnibwapi.getOrderType(151);
	    JunkYardDog = jnibwapi.getOrderType(152);
	    Fatal = jnibwapi.getOrderType(153);
	    None = jnibwapi.getOrderType(154);
	    Unknown = jnibwapi.getOrderType(155);
    }
}
