package sk.hackcraft.bwu;

import javabot.JNIBWAPI;
import javabot.types.TechType;

public class TechTypes {
	final public TechType Stim_Packs;
	final public TechType Lockdown;
	final public TechType EMP_Shockwave;
	final public TechType Spider_Mines;
	final public TechType Scanner_Sweep;
	final public TechType Tank_Siege_Mode;
	final public TechType Defensive_Matrix;
	final public TechType Irradiate;
	final public TechType Yamato_Gun;
	final public TechType Cloaking_Field;
	final public TechType Personnel_Cloaking;
	final public TechType Burrowing;
	final public TechType Infestation;
	final public TechType Spawn_Broodlings;
	final public TechType Dark_Swarm;
	final public TechType Plague;
	final public TechType Consume;
	final public TechType Ensnare;
	final public TechType Parasite;
	final public TechType Psionic_Storm;
	final public TechType Hallucination;
	final public TechType Recall;
	final public TechType Stasis_Field;
	final public TechType Archon_Warp;
	final public TechType Restoration;
	final public TechType Disruption_Web;
	final public TechType Undefined26;
	final public TechType Mind_Control;
	final public TechType Dark_Archon_Meld;
	final public TechType Feedback;
	final public TechType Optical_Flare;
	final public TechType Maelstrom;
	final public TechType Lurker_Aspect;
	final public TechType Undefined33;
	final public TechType Healing;
	final public TechType Undefined35;
	final public TechType Undefined36;
	final public TechType Undefined37;
	final public TechType Undefined38;
	final public TechType Undefined39;
	final public TechType Undefined40;
	final public TechType Undefined41;
	final public TechType Undefined42;
	final public TechType Undefined43;
	final public TechType None;
	final public TechType Unknown;
	final public TechType Nuclear_Strike;
	
	protected TechTypes(JNIBWAPI jnibwapi) {
		Stim_Packs = jnibwapi.getTechType(0);
		Lockdown = jnibwapi.getTechType(1);
		EMP_Shockwave = jnibwapi.getTechType(2);
		Spider_Mines = jnibwapi.getTechType(3);
		Scanner_Sweep = jnibwapi.getTechType(4);
		Tank_Siege_Mode = jnibwapi.getTechType(5);
		Defensive_Matrix = jnibwapi.getTechType(6);
		Irradiate = jnibwapi.getTechType(7);
		Yamato_Gun = jnibwapi.getTechType(8);
		Cloaking_Field = jnibwapi.getTechType(9);
		Personnel_Cloaking = jnibwapi.getTechType(10);
		Burrowing = jnibwapi.getTechType(11);
		Infestation = jnibwapi.getTechType(12);
		Spawn_Broodlings = jnibwapi.getTechType(13);
		Dark_Swarm = jnibwapi.getTechType(14);
		Plague = jnibwapi.getTechType(15);
		Consume = jnibwapi.getTechType(16);
		Ensnare = jnibwapi.getTechType(17);
		Parasite = jnibwapi.getTechType(18);
		Psionic_Storm = jnibwapi.getTechType(19);
		Hallucination = jnibwapi.getTechType(20);
		Recall = jnibwapi.getTechType(21);
		Stasis_Field = jnibwapi.getTechType(22);
		Archon_Warp = jnibwapi.getTechType(23);
		Restoration = jnibwapi.getTechType(24);
		Disruption_Web = jnibwapi.getTechType(25);
		Undefined26 = jnibwapi.getTechType(26);
		Mind_Control = jnibwapi.getTechType(27);
		Dark_Archon_Meld = jnibwapi.getTechType(28);
		Feedback = jnibwapi.getTechType(29);
		Optical_Flare = jnibwapi.getTechType(30);
		Maelstrom = jnibwapi.getTechType(31);
		Lurker_Aspect = jnibwapi.getTechType(32);
		Undefined33 = jnibwapi.getTechType(33);
		Healing = jnibwapi.getTechType(34);
		Undefined35 = jnibwapi.getTechType(35);
		Undefined36 = jnibwapi.getTechType(36);
		Undefined37 = jnibwapi.getTechType(37);
		Undefined38 = jnibwapi.getTechType(38);
		Undefined39 = jnibwapi.getTechType(39);
		Undefined40 = jnibwapi.getTechType(40);
		Undefined41 = jnibwapi.getTechType(41);
		Undefined42 = jnibwapi.getTechType(42);
		Undefined43 = jnibwapi.getTechType(43);
		None = jnibwapi.getTechType(44);
		Unknown = jnibwapi.getTechType(45);
		Nuclear_Strike = jnibwapi.getTechType(46);		
	}
}
