package sk.hackcraft.bwu;

import javabot.JNIBWAPI;
import javabot.types.WeaponType;

public class WeaponTypes {
	final public WeaponType Gauss_Rifle;
	final public WeaponType Gauss_Rifle_Jim_Raynor;
	final public WeaponType C_10_Canister_Rifle;
	final public WeaponType C_10_Canister_Rifle_Sarah_Kerrigan;
	final public WeaponType Fragmentation_Grenade;
	final public WeaponType Fragmentation_Grenade_Jim_Raynor;
	final public WeaponType Spider_Mines;
	final public WeaponType Twin_Autocannons;
	final public WeaponType Hellfire_Missile_Pack;
	final public WeaponType Twin_Autocannons_Alan_Schezar;
	final public WeaponType Hellfire_Missile_Pack_Alan_Schezar;
	final public WeaponType Arclite_Cannon;
	final public WeaponType Arclite_Cannon_Edmund_Duke;
	final public WeaponType Fusion_Cutter;
	final public WeaponType Undefined14;
	final public WeaponType Gemini_Missiles;
	final public WeaponType Burst_Lasers;
	final public WeaponType Gemini_Missiles_Tom_Kazansky;
	final public WeaponType Burst_Lasers_Tom_Kazansky;
	final public WeaponType ATS_Laser_Battery;
	final public WeaponType ATA_Laser_Battery;
	final public WeaponType ATS_Laser_Battery_Hero;
	final public WeaponType ATA_Laser_Battery_Hero;
	final public WeaponType ATS_Laser_Battery_Hyperion;
	final public WeaponType ATA_Laser_Battery_Hyperion;
	final public WeaponType Flame_Thrower;
	final public WeaponType Flame_Thrower_Gui_Montag;
	final public WeaponType Arclite_Shock_Cannon;
	final public WeaponType Arclite_Shock_Cannon_Edmund_Duke;
	final public WeaponType Longbolt_Missile;
	final public WeaponType Yamato_Gun;
	final public WeaponType Nuclear_Strike;
	final public WeaponType Lockdown;
	final public WeaponType EMP_Shockwave;
	final public WeaponType Irradiate;
	final public WeaponType Claws;
	final public WeaponType Claws_Devouring_One;
	final public WeaponType Claws_Infested_Kerrigan;
	final public WeaponType Needle_Spines;
	final public WeaponType Needle_Spines_Hunter_Killer;
	final public WeaponType Kaiser_Blades;
	final public WeaponType Kaiser_Blades_Torrasque;
	final public WeaponType Toxic_Spores;
	final public WeaponType Spines;
	final public WeaponType Undefined44;
	final public WeaponType Undefined45;
	final public WeaponType Acid_Spore;
	final public WeaponType Acid_Spore_Kukulza;
	final public WeaponType Glave_Wurm;
	final public WeaponType Glave_Wurm_Kukulza;
	final public WeaponType Undefined50;
	final public WeaponType Undefined51;
	final public WeaponType Seeker_Spores;
	final public WeaponType Subterranean_Tentacle;
	final public WeaponType Suicide_Infested_Terran;
	final public WeaponType Suicide_Scourge;
	final public WeaponType Parasite;
	final public WeaponType Spawn_Broodlings;
	final public WeaponType Ensnare;
	final public WeaponType Dark_Swarm;
	final public WeaponType Plague;
	final public WeaponType Consume;
	final public WeaponType Particle_Beam;
	final public WeaponType Undefined63;
	final public WeaponType Psi_Blades;
	final public WeaponType Psi_Blades_Fenix;
	final public WeaponType Phase_Disruptor;
	final public WeaponType Phase_Disruptor_Fenix;
	final public WeaponType Undefined68;
	final public WeaponType Psi_Assault;
	final public WeaponType Psionic_Shockwave;
	final public WeaponType Psionic_Shockwave_Tassadar_Zeratul_Archon;
	final public WeaponType Undefined72;
	final public WeaponType Dual_Photon_Blasters;
	final public WeaponType Anti_Matter_Missiles;
	final public WeaponType Dual_Photon_Blasters_Mojo;
	final public WeaponType Anti_Matter_Missiles_Mojo;
	final public WeaponType Phase_Disruptor_Cannon;
	final public WeaponType Phase_Disruptor_Cannon_Danimoth;
	final public WeaponType Pulse_Cannon;
	final public WeaponType STS_Photon_Cannon;
	final public WeaponType STA_Photon_Cannon;
	final public WeaponType Scarab;
	final public WeaponType Stasis_Field;
	final public WeaponType Psionic_Storm;
	final public WeaponType Warp_Blades_Zeratul;
	final public WeaponType Warp_Blades_Hero;
	final public WeaponType Undefined87;
	final public WeaponType Undefined88;
	final public WeaponType Undefined89;
	final public WeaponType Undefined90;
	final public WeaponType Undefined91;
	final public WeaponType Undefined92;
	final public WeaponType Undefined93;
	final public WeaponType Undefined94;
	final public WeaponType Undefined95;
	final public WeaponType Undefined96;
	final public WeaponType Undefined97;
	final public WeaponType Undefined98;
	final public WeaponType Undefined99;
	final public WeaponType Neutron_Flare;
	final public WeaponType Disruption_Web;
	final public WeaponType Restoration;
	final public WeaponType Halo_Rockets;
	final public WeaponType Corrosive_Acid;
	final public WeaponType Mind_Control;
	final public WeaponType Feedback;
	final public WeaponType Optical_Flare;
	final public WeaponType Maelstrom;
	final public WeaponType Subterranean_Spines;
	final public WeaponType Undefined110;
	final public WeaponType Warp_Blades;
	final public WeaponType C_10_Canister_Rifle_Samir_Duran;
	final public WeaponType C_10_Canister_Rifle_Infested_Duran;
	final public WeaponType Dual_Photon_Blasters_Artanis;
	final public WeaponType Anti_Matter_Missiles_Artanis;
	final public WeaponType C_10_Canister_Rifle_Alexei_Stukov;
	final public WeaponType Undefined117;
	final public WeaponType Undefined118;
	final public WeaponType Undefined119;
	final public WeaponType Undefined120;
	final public WeaponType Undefined121;
	final public WeaponType Undefined122;
	final public WeaponType Undefined123;
	final public WeaponType Undefined124;
	final public WeaponType Undefined125;
	final public WeaponType Undefined126;
	final public WeaponType Undefined127;
	final public WeaponType Undefined128;
	final public WeaponType Undefined129;
	final public WeaponType None;
	final public WeaponType Unknown;
	
	protected WeaponTypes(JNIBWAPI jnibwapi) {
		Gauss_Rifle = jnibwapi.getWeaponType(0);
		Gauss_Rifle_Jim_Raynor = jnibwapi.getWeaponType(1);
		C_10_Canister_Rifle = jnibwapi.getWeaponType(2);
		C_10_Canister_Rifle_Sarah_Kerrigan = jnibwapi.getWeaponType(3);
		Fragmentation_Grenade = jnibwapi.getWeaponType(4);
		Fragmentation_Grenade_Jim_Raynor = jnibwapi.getWeaponType(5);
		Spider_Mines = jnibwapi.getWeaponType(6);
		Twin_Autocannons = jnibwapi.getWeaponType(7);
		Hellfire_Missile_Pack = jnibwapi.getWeaponType(8);
		Twin_Autocannons_Alan_Schezar = jnibwapi.getWeaponType(9);
		Hellfire_Missile_Pack_Alan_Schezar = jnibwapi.getWeaponType(10);
		Arclite_Cannon = jnibwapi.getWeaponType(11);
		Arclite_Cannon_Edmund_Duke = jnibwapi.getWeaponType(12);
		Fusion_Cutter = jnibwapi.getWeaponType(13);
		Undefined14 = jnibwapi.getWeaponType(14);
		Gemini_Missiles = jnibwapi.getWeaponType(15);
		Burst_Lasers = jnibwapi.getWeaponType(16);
		Gemini_Missiles_Tom_Kazansky = jnibwapi.getWeaponType(17);
		Burst_Lasers_Tom_Kazansky = jnibwapi.getWeaponType(18);
		ATS_Laser_Battery = jnibwapi.getWeaponType(19);
		ATA_Laser_Battery = jnibwapi.getWeaponType(20);
		ATS_Laser_Battery_Hero = jnibwapi.getWeaponType(21);
		ATA_Laser_Battery_Hero = jnibwapi.getWeaponType(22);
		ATS_Laser_Battery_Hyperion = jnibwapi.getWeaponType(23);
		ATA_Laser_Battery_Hyperion = jnibwapi.getWeaponType(24);
		Flame_Thrower = jnibwapi.getWeaponType(25);
		Flame_Thrower_Gui_Montag = jnibwapi.getWeaponType(26);
		Arclite_Shock_Cannon = jnibwapi.getWeaponType(27);
		Arclite_Shock_Cannon_Edmund_Duke = jnibwapi.getWeaponType(28);
		Longbolt_Missile = jnibwapi.getWeaponType(29);
		Yamato_Gun = jnibwapi.getWeaponType(30);
		Nuclear_Strike = jnibwapi.getWeaponType(31);
		Lockdown = jnibwapi.getWeaponType(32);
		EMP_Shockwave = jnibwapi.getWeaponType(33);
		Irradiate = jnibwapi.getWeaponType(34);
		Claws = jnibwapi.getWeaponType(35);
		Claws_Devouring_One = jnibwapi.getWeaponType(36);
		Claws_Infested_Kerrigan = jnibwapi.getWeaponType(37);
		Needle_Spines = jnibwapi.getWeaponType(38);
		Needle_Spines_Hunter_Killer = jnibwapi.getWeaponType(39);
		Kaiser_Blades = jnibwapi.getWeaponType(40);
		Kaiser_Blades_Torrasque = jnibwapi.getWeaponType(41);
		Toxic_Spores = jnibwapi.getWeaponType(42);
		Spines = jnibwapi.getWeaponType(43);
		Undefined44 = jnibwapi.getWeaponType(44);
		Undefined45 = jnibwapi.getWeaponType(45);
		Acid_Spore = jnibwapi.getWeaponType(46);
		Acid_Spore_Kukulza = jnibwapi.getWeaponType(47);
		Glave_Wurm = jnibwapi.getWeaponType(48);
		Glave_Wurm_Kukulza = jnibwapi.getWeaponType(49);
		Undefined50 = jnibwapi.getWeaponType(50);
		Undefined51 = jnibwapi.getWeaponType(51);
		Seeker_Spores = jnibwapi.getWeaponType(52);
		Subterranean_Tentacle = jnibwapi.getWeaponType(53);
		Suicide_Infested_Terran = jnibwapi.getWeaponType(54);
		Suicide_Scourge = jnibwapi.getWeaponType(55);
		Parasite = jnibwapi.getWeaponType(56);
		Spawn_Broodlings = jnibwapi.getWeaponType(57);
		Ensnare = jnibwapi.getWeaponType(58);
		Dark_Swarm = jnibwapi.getWeaponType(59);
		Plague = jnibwapi.getWeaponType(60);
		Consume = jnibwapi.getWeaponType(61);
		Particle_Beam = jnibwapi.getWeaponType(62);
		Undefined63 = jnibwapi.getWeaponType(63);
		Psi_Blades = jnibwapi.getWeaponType(64);
		Psi_Blades_Fenix = jnibwapi.getWeaponType(65);
		Phase_Disruptor = jnibwapi.getWeaponType(66);
		Phase_Disruptor_Fenix = jnibwapi.getWeaponType(67);
		Undefined68 = jnibwapi.getWeaponType(68);
		Psi_Assault = jnibwapi.getWeaponType(69);
		Psionic_Shockwave = jnibwapi.getWeaponType(70);
		Psionic_Shockwave_Tassadar_Zeratul_Archon = jnibwapi.getWeaponType(71);
		Undefined72 = jnibwapi.getWeaponType(72);
		Dual_Photon_Blasters = jnibwapi.getWeaponType(73);
		Anti_Matter_Missiles = jnibwapi.getWeaponType(74);
		Dual_Photon_Blasters_Mojo = jnibwapi.getWeaponType(75);
		Anti_Matter_Missiles_Mojo = jnibwapi.getWeaponType(76);
		Phase_Disruptor_Cannon = jnibwapi.getWeaponType(77);
		Phase_Disruptor_Cannon_Danimoth = jnibwapi.getWeaponType(78);
		Pulse_Cannon = jnibwapi.getWeaponType(79);
		STS_Photon_Cannon = jnibwapi.getWeaponType(80);
		STA_Photon_Cannon = jnibwapi.getWeaponType(81);
		Scarab = jnibwapi.getWeaponType(82);
		Stasis_Field = jnibwapi.getWeaponType(83);
		Psionic_Storm = jnibwapi.getWeaponType(84);
		Warp_Blades_Zeratul = jnibwapi.getWeaponType(85);
		Warp_Blades_Hero = jnibwapi.getWeaponType(86);
		Undefined87 = jnibwapi.getWeaponType(87);
		Undefined88 = jnibwapi.getWeaponType(88);
		Undefined89 = jnibwapi.getWeaponType(89);
		Undefined90 = jnibwapi.getWeaponType(90);
		Undefined91 = jnibwapi.getWeaponType(91);
		Undefined92 = jnibwapi.getWeaponType(92);
		Undefined93 = jnibwapi.getWeaponType(93);
		Undefined94 = jnibwapi.getWeaponType(94);
		Undefined95 = jnibwapi.getWeaponType(95);
		Undefined96 = jnibwapi.getWeaponType(96);
		Undefined97 = jnibwapi.getWeaponType(97);
		Undefined98 = jnibwapi.getWeaponType(98);
		Undefined99 = jnibwapi.getWeaponType(99);
		Neutron_Flare = jnibwapi.getWeaponType(100);
		Disruption_Web = jnibwapi.getWeaponType(101);
		Restoration = jnibwapi.getWeaponType(102);
		Halo_Rockets = jnibwapi.getWeaponType(103);
		Corrosive_Acid = jnibwapi.getWeaponType(104);
		Mind_Control = jnibwapi.getWeaponType(105);
		Feedback = jnibwapi.getWeaponType(106);
		Optical_Flare = jnibwapi.getWeaponType(107);
		Maelstrom = jnibwapi.getWeaponType(108);
		Subterranean_Spines = jnibwapi.getWeaponType(109);
		Undefined110 = jnibwapi.getWeaponType(110);
		Warp_Blades = jnibwapi.getWeaponType(111);
		C_10_Canister_Rifle_Samir_Duran = jnibwapi.getWeaponType(112);
		C_10_Canister_Rifle_Infested_Duran = jnibwapi.getWeaponType(113);
		Dual_Photon_Blasters_Artanis = jnibwapi.getWeaponType(114);
		Anti_Matter_Missiles_Artanis = jnibwapi.getWeaponType(115);
		C_10_Canister_Rifle_Alexei_Stukov = jnibwapi.getWeaponType(116);
		Undefined117 = jnibwapi.getWeaponType(117);
		Undefined118 = jnibwapi.getWeaponType(118);
		Undefined119 = jnibwapi.getWeaponType(119);
		Undefined120 = jnibwapi.getWeaponType(120);
		Undefined121 = jnibwapi.getWeaponType(121);
		Undefined122 = jnibwapi.getWeaponType(122);
		Undefined123 = jnibwapi.getWeaponType(123);
		Undefined124 = jnibwapi.getWeaponType(124);
		Undefined125 = jnibwapi.getWeaponType(125);
		Undefined126 = jnibwapi.getWeaponType(126);
		Undefined127 = jnibwapi.getWeaponType(127);
		Undefined128 = jnibwapi.getWeaponType(128);
		Undefined129 = jnibwapi.getWeaponType(129);
		None = jnibwapi.getWeaponType(130);
		Unknown = jnibwapi.getWeaponType(131);	
	}
}
